<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="configuration" nsURI="http://org.eclipse.incquery/viewmodel/configuration/1.0"
    nsPrefix="org.eclipse.incquery.viewmodel.configuration">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="settingDelegates" value="org.eclipse.viatra.query.querybasedfeature"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleDescriptors" upperBound="-1"
        eType="#//RuleDescriptor" containment="true" eOpposite="#//RuleDescriptor/configuration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementRuleDescriptors"
        upperBound="-1" eType="#//ElementRuleDescriptor" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="org.eclipse.viatra.query.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.configuration_elementRuleDescriptors"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuralFeatureRuleDescriptors"
        upperBound="-1" eType="#//StructuralFeatureRuleDescriptor" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="org.eclipse.viatra.query.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.configuration_structuralFeatureRuleDescriptors"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceRuleDescriptors"
        upperBound="-1" eType="#//ReferenceRuleDescriptor" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="org.eclipse.viatra.query.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.configuration_referenceRuleDescriptors"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeRuleDescriptors"
        upperBound="-1" eType="#//AttributeRuleDescriptor" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="org.eclipse.viatra.query.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.configuration_attributeRuleDescriptors"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceModelURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetModelURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternResources" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternResourceURIs" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationRuleDescriptors"
        upperBound="-1" eType="#//TransformationRuleDescriptor" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="org.eclipse.viatra.query.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.configuration_transformationRuleDescriptors"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceabilityRuleDescriptors"
        upperBound="-1" eType="#//TraceabilityRuleDescriptor" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="org.eclipse.viatra.query.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.configuration_traceabilityRuleDescriptors"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hiddenParametersRuleDescriptors"
        upperBound="-1" eType="#//HiddenParametersRuleDescriptor" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="org.eclipse.viatra.query.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.configuration_hiddenParametersRuleDescriptors"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheduler" lowerBound="1"
        eType="#//Scheduler"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enableDetailedTraceability"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementRuleDescriptor" eSuperTypes="#//TransformationRuleDescriptor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuralFeatureRuleDescriptors"
        upperBound="-1" eType="#//StructuralFeatureRuleDescriptor" eOpposite="#//StructuralFeatureRuleDescriptor/ownerElementRuleDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceRuleDescriptors"
        upperBound="-1" eType="#//ReferenceRuleDescriptor" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="org.eclipse.viatra.query.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.elementRule_referenceRuleDescriptors"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeRuleDescriptors"
        upperBound="-1" eType="#//AttributeRuleDescriptor" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="org.eclipse.viatra.query.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.elementRule_attributeRuleDescriptors"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralFeatureRuleDescriptor" abstract="true"
      eSuperTypes="#//TransformationRuleDescriptor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownerElementRuleDescriptor"
        lowerBound="1" eType="#//ElementRuleDescriptor" eOpposite="#//ElementRuleDescriptor/structuralFeatureRuleDescriptors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patternParameterMappings"
        upperBound="-1" eType="#//PatternParameterMapping" containment="true" eOpposite="#//PatternParameterMapping/structuralFeatureRuleDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceElementParameterMappings"
        upperBound="-1" eType="#//PatternParameterMapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleDescriptor" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="1"
        eType="#//Configuration" eOpposite="#//Configuration/ruleDescriptors"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternFQN" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceRuleDescriptor" eSuperTypes="#//StructuralFeatureRuleDescriptor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetElementRuleDescriptor"
        lowerBound="1" eType="#//ElementRuleDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetElementParameterMappings"
        upperBound="-1" eType="#//PatternParameterMapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeRuleDescriptor" eSuperTypes="#//StructuralFeatureRuleDescriptor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="calculatedPatternParameterName"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true">
      <eAnnotations>
        <details key="get" value="return org.eclipse.incquery.viewmodel.configuration.util.ConfigurationModelUtil.getInstance(this).getDerivedName(this);"/>
      </eAnnotations>
      <eAnnotations source="org.eclipse.viatra.query.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.namedElement_name"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternParameterMapping" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sfRulePatternParameterName"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eRulePatternParameterName"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuralFeatureRuleDescriptor"
        lowerBound="1" eType="#//StructuralFeatureRuleDescriptor" eOpposite="#//StructuralFeatureRuleDescriptor/patternParameterMappings"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationRuleDescriptor" abstract="true"
      eSuperTypes="#//RuleDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceabilityRuleDescriptor" abstract="true"
      eSuperTypes="#//RuleDescriptor"/>
  <eClassifiers xsi:type="ecore:EClass" name="HiddenParametersRuleDescriptor" eSuperTypes="#//TraceabilityRuleDescriptor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originalPatternFQN" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationRuleDescriptors"
        upperBound="-1" eType="#//TransformationRuleDescriptor" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="org.eclipse.viatra.query.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.hiddenParametersRuleDescriptors_transformationRuleDescriptors"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Scheduler">
    <eLiterals name="UPDATE_COMPLETE_BASED" literal="UpdateCompleteBased"/>
    <eLiterals name="TRANSACTIONAL" value="1" literal="Transactional"/>
    <eLiterals name="MANUAL" value="2" literal="Manual"/>
  </eClassifiers>
</ecore:EPackage>
