<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="configuration" nsURI="http://org.eclipse.incquery/viewmodel/configuration/1.0"
    nsPrefix="org.eclipse.incquery.viewmodel.configuration">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="settingDelegates" value="org.eclipse.incquery.querybasedfeature"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetMetamodelNsURI" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceModel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetModel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResource"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//Rule" containment="true" eOpposite="#//Rule/configuration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementRules" upperBound="-1"
        eType="#//ElementRule" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.configuration_elementRules"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuralFeatureRules"
        upperBound="-1" eType="#//StructuralFeatureRule" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.configuration_structuralFeatureRules"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceRules" upperBound="-1"
        eType="#//ReferenceRule" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.configuration_referenceRules"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeRules" upperBound="-1"
        eType="#//AttributeRule" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.configuration_attributeRules"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementRule" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuralFeatureRules"
        upperBound="-1" eType="#//StructuralFeatureRule" eOpposite="#//StructuralFeatureRule/ownerElementRule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceRules" upperBound="-1"
        eType="#//ReferenceRule" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.elementRule_referenceRules"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeRules" upperBound="-1"
        eType="#//AttributeRule" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.configuration.patterns.elementRule_attributeRules"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralFeatureRule" abstract="true"
      eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownerElementRule" lowerBound="1"
        eType="#//ElementRule" eOpposite="#//ElementRule/structuralFeatureRules"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" lowerBound="1"
        eType="#//Configuration" eOpposite="#//Configuration/rules"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternFQN" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceRule" eSuperTypes="#//StructuralFeatureRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceElementPatternVariables"
        lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetElementPatternVariables"
        lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetElementRule" lowerBound="1"
        eType="#//ElementRule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeRule" eSuperTypes="#//StructuralFeatureRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="calculatedPatternVariable"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceElementPatternVariables"
        lowerBound="1" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
