<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="traceability" nsURI="http://org.eclipse.incquery/viewmodel/traceability/3.0"
    nsPrefix="org.eclipse.incquery.viewmodel.traceability">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="settingDelegates" value="org.eclipse.incquery.querybasedfeature"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Traceability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="traces" upperBound="-1"
        eType="#//Trace" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//TraceTarget" containment="true" eOpposite="#//TraceTarget/trace"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruleDescriptorId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sources" lowerBound="1"
        upperBound="-1" eType="#//TraceSource" containment="true" eOpposite="#//TraceSource/trace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hiddenSources" upperBound="-1"
        eType="#//TraceSource" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.traceability.patterns.trace_hiddenSources"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eObjectSources" upperBound="-1"
        eType="#//EObjectSource" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.traceability.patterns.trace_eObjectSources"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="javaObjectSources" upperBound="-1"
        eType="#//JavaObjectSource" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.traceability.patterns.trace_javaObjectSources"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceSources" upperBound="-1"
        eType="#//ReferenceSource" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.traceability.patterns.trace_referenceSources"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeSources" upperBound="-1"
        eType="#//AttributeSource" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.traceability.patterns.trace_attributeSources"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visibleSources" lowerBound="1"
        upperBound="-1" eType="#//TraceSource" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="org.eclipse.incquery.querybasedfeature">
        <details key="patternFQN" value="org.eclipse.incquery.viewmodel.traceability.patterns.trace_visibleSources"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceSource" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternParameterName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hidden" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trace" lowerBound="1" eType="#//Trace"
        eOpposite="#//Trace/sources"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenced" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong" defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectSource" eSuperTypes="#//TraceSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
        eType="#//ReferenceSource" containment="true" eOpposite="#//ReferenceSource/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//AttributeSource" containment="true" eOpposite="#//AttributeSource/owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaObjectSource" eSuperTypes="#//TraceSource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//EObjectSource"
        eOpposite="#//EObjectSource/references"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//EObjectSource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeSource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//EObjectSource"
        eOpposite="#//EObjectSource/attributes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//JavaObjectSource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceTarget" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trace" lowerBound="1" eType="#//Trace"
        eOpposite="#//Trace/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectTarget" eSuperTypes="#//TraceTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceTarget" eSuperTypes="#//TraceTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//EObjectTarget"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//EObjectTarget"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeTarget" eSuperTypes="#//TraceTarget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//EObjectTarget"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
</ecore:EPackage>
